# Generated by Django 4.2.23 on 2025-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('brands', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
