# Generated by Django 4.2.23 on 2025-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True)),
                ('brands', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('countries', models.TextField(blank=True)),
                ('quantity', models.TextField(blank=True)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
